# Attention: if you submit an improvement for a Namecoin Cirrus config, please
# file a GitHub issue about it at the namecoin/meta repo, so that we can make
# sure it propagates to all the other Namecoin repos.  Thanks!

task:
  name: ShellCheck
  container:
    image: fedora:latest
    cpu: 1
    memory: 1G
  install_script: dnf install -y ShellCheck
  lint_script: bash testdata/shellcheck.bash

task:
  name: "Cross-Compile Go $GO_VERSION$MODULES_NAME"
  alias: Cross-Compile
  container:
    image: golang:$GO_VERSION
    cpu: 8
    memory: 8G
  install_script:
    - apt-get update
    - apt-get install -y git patch
  coredns_script:
    - git clone https://github.com/coredns/coredns-utils.git
    - cd coredns-utils
    - patch -p1 < ../ZSK.patch
  path_script:
    - cd coredns-utils
    - source ../testdata/move_to_gopath.bash
  matrix:
    - env:
        GO111MODULE: "off"
        MODULES_NAME: " Modules Off"
      gox_script:
        - go get github.com/mitchellh/gox
      fetch_script:
        - go get -tags "$GOX_TAGS" -d -v -t github.com/coredns/coredns-utils/...
    - env:
        MODULES_NAME: ""
      # TODO: Remove this line after upstream issue #5 is fixed.
      allow_failures: true
      gox_script:
        - go install github.com/mitchellh/gox@latest
      fetch_script:
        - cd $(go env GOPATH)/src/github.com/"coredns/coredns-utils"
        - go mod tidy
  build_script:
    - rm -rf idist
    - cd $(go env GOPATH)/src/github.com/"coredns/coredns-utils"
    - CGO_ENABLED=0 gox -tags="$GOX_TAGS" -parallel=8 -osarch 'darwin/amd64 freebsd/386 freebsd/amd64 freebsd/arm linux/386 linux/amd64 linux/arm linux/arm64 linux/ppc64 linux/ppc64le openbsd/386 openbsd/amd64 netbsd/386 netbsd/amd64 netbsd/arm dragonfly/amd64 solaris/amd64 windows/386 windows/amd64' -output "$GOPATH/releasing/idist/$CIRRUS_REPO_NAME-$CIRRUS_TAG-{{.OS}}_{{.Arch}}/bin/{{.Dir}}" ./...
  dist_script:
    - mv $GOPATH/releasing/idist ./idist
    - bash "testdata/dist.bash"
  binaries_artifacts:
    path: "dist/*"
  env:
    GOX_TAGS: ""
    GO_VERSION: latest

# TODO: Add Windows unit tests

# TODO: "Testing config parsing" from travis.bash

# TODO: Add multiple Go versions to Gox builds and unit tests

# TODO: Add debug stripping and path stripping to Gox for repro builds

# TODO: Re-add darwin/386 for old Go versions where it was supported

# TODO: Fix upload repo for tagged commits (don't use Nightly repo for this)

# TODO: Skip Signify and Release if it's not applicable

# TODO: Signify Nightlies

# TODO: IRC notifications on failure

# TODO: Cron
